api:
  insecure: false

entrypoints:
  web:
    address: ":80"
  websecurity:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  myresolver:
    acme:
      email: "pedro.nec@hotmail.com"
      storage: /acme.json
      httpChallenge:
        entrypoint: web

log:
  filePath: "/traefik.log"
  level: ERROR
  format: json